# TODO: Eval is required for the .homesickrc feature. This should eventually be
# removed if the feature is implemented in a more secure way.
Eval:
  Enabled: false

# TODO: The following settings disable reports about issues that can be fixed
# through refactoring. Remove these as offenses are removed from the code base.

ClassLength:
  Enabled: false

CyclomaticComplexity:
  Max: 16

LineLength:
  Max: 174

MethodLength:
  Max: 31
